language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly
  - 1.33.0

os:
  - linux
  - windows
  - osx

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo clean
  - cargo build
  - cargo test
